# Visit https://github.com/lowlighter/metrics for full reference
name: Metrics Isocalendar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          user: Chefcurry4
          
          # Your token
          token: ${{ secrets.METRICS_TOKEN }}

          # More options
          base: "" # Do not count private contributions
          config_timezone: America/New_York # Set your timezone

          # Enable the isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Show a full year

          # Output file name
          filename: metrics.plugin.isocalendar.svg
